.TH COREWAR 1
.SH NAME
corewar -- a virtual machine to run the corewar battles
.SH SYNOPSIS
.B ./corewar
[-d/g/n/s/b] [(\fB\-n\fR\ \fIchampions.cor\fR)]
.SH DESCRIPTION
.B corewar
runs one or more champions in a virtual machine
.SH OPTIONS
 -d --dump [int] dump memory after int cycles
 -g graphic ncurse rendering mode
 -n [int] specify player number
 -s [int] save output mode
 -b [int] debug mode
.SH AUTHOR
brocher & allallem
